### ISSUE TITLE
Consider moving paths into a separate module

### ISSUE THREAD

**Issue by adnasa** [vutran/dext-core-utils#18]
We should consider moving `path.js` into a separate module to be update in __one__ place and used where we need it

Because here is how the following dependency tree looks like:

lib               |   depends on path
---               |   ---
dext              |   ✓
dext-core-utils   |   ✓
dext-cli          |   ✓

lib               |   depends on dext-core-utils
---               |   ---
dext              |   ╳
dext-cli          |   ✓

lib               |   depends on dext-cli
---               |   ---
dext              |   ╳
dext-core-utils   |   ╳

---

### Alternative

Another option is remove `path` from <kbd>dext</kbd> and have <kbd>dext-core-utils</kbd> as a dependency even on production build

**Comment by vutran** [comment]
> Another option is remove path from dext and have dext-core-utils as a dependency even on production build

This would be the best option since we'll most likely incorporate the core utils functions to modify config within the Dext app itself eventually either through a core plugin or some sort of system prefs window.

**Comment by adnasa** [comment]
Closing this since I consider this question resolved
